exclude: '^(external|build|.vscode)/.*'
default_language_version:
    python: python3.11
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
        exclude: '^.vscode/.*'
    -   id: check-ast
    -   id: check-merge-conflict
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
    -   id: clang-format
-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    -   id: cmake-format
        additional_dependencies: [pyyaml]
